version: '3.8'

services:
  proyectoprueba: # Nombre de la aplicación (lo que aparece en application.properties)
    build: ./proyectoPrueba  # Nombre de la carpeta donde está el Dockerfile
    mem_limit: 512m
    ports:
      - "8081:8081"
    environment:
      DB_URL: "mem:testdb"  # Base de datos en memoria (predeterminado)
      DB_USER: sa
      DB_PASSWORD: password
    restart: always
    #depends_on:
      #- app_pruebajava # Cambié esto a la forma correcta

# Comentar el servicio 'app_pruebajava' ya que no lo estamos usando para H2
# app_pruebajava:
#   image: postgres:latest  # Esto se descomenta si cambias a Postgres más tarde
#   ports:
#     - "3307:3306"
#   environment:
#     MYSQL_ROOT_PASSWORD: 1234
#     MYSQL_PASSWORD: 1234
#     MYSQL_DATABASE: app_pruebajava
#   restart: always
#   healthcheck:
#     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#     timeout: 10s
#     retries: 10